import { Store, ShippingRate, BggGame, GameBarcode, MerchantProductMapping, StoreGameOffer, QueueItem } from '@/types';

export const INITIAL_STORES: Store[] = [
  {
    id: 'store-ficha-01',
    name: 'Ficha y Dado',
    logo_url: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.90,
    review_count: 128,
    feed_url: 'https://fichaydado.com/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 420,
    feed_last_matched_count: 412,
  },
  {
    id: 'store-mundomeeple-02',
    name: 'Mundo Meeple Store',
    logo_url: 'https://images.unsplash.com/photo-1563941402622-4e7a488bcc57?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.85,
    review_count: 95,
    feed_url: 'https://mundomeeplestore.com/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 310,
    feed_last_matched_count: 305,
  },
  {
    id: 'store-rollgames-03',
    name: 'Roll Games',
    logo_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.75,
    review_count: 64,
    feed_url: 'https://rollgames.mx/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 180,
    feed_last_matched_count: 175,
  },
  {
    id: 'store-tlacuache-04',
    name: 'Con T de Tlacuache',
    logo_url: 'https://images.unsplash.com/photo-1585504198199-20277593b94f?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.88,
    review_count: 72,
    feed_url: 'https://tdetlacuache.com/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 210,
    feed_last_matched_count: 204,
  },
  {
    id: 'store-quantum-05',
    name: 'Quantum Boardgames',
    logo_url: 'https://images.unsplash.com/photo-1585504198199-20277593b94f?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.92,
    review_count: 88,
    feed_url: 'https://quantumboardgames.com/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 250,
    feed_last_matched_count: 242,
  },
  {
    id: 'store-alfaydelta-06',
    name: 'Alfa y Delta',
    logo_url: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.80,
    review_count: 52,
    feed_url: 'https://alfaydelta.com/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 160,
    feed_last_matched_count: 155,
  },
  {
    id: 'store-bundaba-07',
    name: 'Bundaba',
    logo_url: 'https://images.unsplash.com/photo-1563941402622-4e7a488bcc57?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.82,
    review_count: 46,
    feed_url: 'https://bundaba.com.mx/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 140,
    feed_last_matched_count: 135,
  },
  {
    id: 'store-geekystuff-08',
    name: 'Geeky Stuff',
    logo_url: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.86,
    review_count: 68,
    feed_url: 'https://geekystuff.com.mx/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 195,
    feed_last_matched_count: 188,
  },
  {
    id: 'store-2tomatoes-09',
    name: '2 Tomatoes MX',
    logo_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.79,
    review_count: 42,
    feed_url: 'https://2tomatoesgames.com.mx/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 120,
    feed_last_matched_count: 115,
  },
  {
    id: 'store-amukiri-10',
    name: 'Amukiri',
    logo_url: 'https://images.unsplash.com/photo-1563941402622-4e7a488bcc57?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.70,
    review_count: 35,
    feed_url: 'https://amukiri.com.mx/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 95,
    feed_last_matched_count: 90,
  },
  {
    id: 'store-avalon-11',
    name: 'Avalon Store',
    logo_url: 'https://images.unsplash.com/photo-1585504198199-20277593b94f?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.84,
    review_count: 58,
    feed_url: 'https://avalonstore.mx/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 175,
    feed_last_matched_count: 170,
  },
  {
    id: 'store-cabala-12',
    name: 'Cábala Games',
    logo_url: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.77,
    review_count: 39,
    feed_url: 'https://cabalagames.mx/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 110,
    feed_last_matched_count: 106,
  },
  {
    id: 'store-catito-13',
    name: 'Catito Games',
    logo_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.89,
    review_count: 63,
    feed_url: 'https://catitogames.com/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 185,
    feed_last_matched_count: 180,
  },
  {
    id: 'store-chocita-14',
    name: 'Chocita Juegos',
    logo_url: 'https://images.unsplash.com/photo-1563941402622-4e7a488bcc57?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.81,
    review_count: 47,
    feed_url: 'https://chocitajuegos.com/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 150,
    feed_last_matched_count: 144,
  },
  {
    id: 'store-demon-15',
    name: 'Demon Juegos',
    logo_url: 'https://images.unsplash.com/photo-1585504198199-20277593b94f?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.78,
    review_count: 41,
    feed_url: 'https://demonjuegos.com/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 130,
    feed_last_matched_count: 126,
  },
  {
    id: 'store-diad-16',
    name: 'Día D Juegos',
    logo_url: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.91,
    review_count: 83,
    feed_url: 'https://diadjuegos.com/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 240,
    feed_last_matched_count: 232,
  },
  {
    id: 'store-eramu-17',
    name: 'Eramu Juegos y Café',
    logo_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.74,
    review_count: 31,
    feed_url: 'https://eramujuegos.com/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 90,
    feed_last_matched_count: 86,
  },
  {
    id: 'store-eximia-18',
    name: 'Eximia Games',
    logo_url: 'https://images.unsplash.com/photo-1563941402622-4e7a488bcc57?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.87,
    review_count: 55,
    feed_url: 'https://eximiagames.com/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 165,
    feed_last_matched_count: 160,
  },
  {
    id: 'store-gamesmart-19',
    name: 'GameSmart',
    logo_url: 'https://images.unsplash.com/photo-1585504198199-20277593b94f?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.83,
    review_count: 49,
    feed_url: 'https://gamesmart.com.mx/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 145,
    feed_last_matched_count: 140,
  },
  {
    id: 'store-geim-20',
    name: 'Geim Puebla',
    logo_url: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.76,
    review_count: 36,
    feed_url: 'https://geimpuebla.com/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 105,
    feed_last_matched_count: 100,
  },
  {
    id: 'store-hobbiton-21',
    name: 'Hobbiton Games',
    logo_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.93,
    review_count: 91,
    feed_url: 'https://hobbitongames.com/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 270,
    feed_last_matched_count: 264,
  },
  {
    id: 'store-hobbyguild-22',
    name: 'Hobby Guild',
    logo_url: 'https://images.unsplash.com/photo-1563941402622-4e7a488bcc57?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.80,
    review_count: 44,
    feed_url: 'https://hobbyguild.mx/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 135,
    feed_last_matched_count: 130,
  },
  {
    id: 'store-imperio-23',
    name: 'Imperio Games',
    logo_url: 'https://images.unsplash.com/photo-1585504198199-20277593b94f?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.85,
    review_count: 53,
    feed_url: 'https://imperiogames.com.mx/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 155,
    feed_last_matched_count: 150,
  },
  {
    id: 'store-ingenioz-24',
    name: 'Ingenioz',
    logo_url: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.72,
    review_count: 29,
    feed_url: 'https://ingenioz.com.mx/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 85,
    feed_last_matched_count: 80,
  },
  {
    id: 'store-juegamas-25',
    name: 'Juega Más',
    logo_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.82,
    review_count: 48,
    feed_url: 'https://juegamas.com.mx/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 140,
    feed_last_matched_count: 135,
  },
  {
    id: 'store-juegateeste-26',
    name: 'Juégate Este',
    logo_url: 'https://images.unsplash.com/photo-1563941402622-4e7a488bcc57?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.78,
    review_count: 37,
    feed_url: 'https://juegateeste.com/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 115,
    feed_last_matched_count: 110,
  },
  {
    id: 'store-belugas-27',
    name: 'Juego de Belugas',
    logo_url: 'https://images.unsplash.com/photo-1585504198199-20277593b94f?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.84,
    review_count: 51,
    feed_url: 'https://juedodebelugas.com/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 150,
    feed_last_matched_count: 145,
  },
  {
    id: 'store-patolli-28',
    name: 'Juegos Patolli',
    logo_url: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.88,
    review_count: 67,
    feed_url: 'https://juegospatolli.com/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 190,
    feed_last_matched_count: 184,
  },
  {
    id: 'store-jugadorinicial-29',
    name: 'Jugador Inicial',
    logo_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.86,
    review_count: 59,
    feed_url: 'https://jugadorinicial.com.mx/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 170,
    feed_last_matched_count: 165,
  },
  {
    id: 'store-jugandoando-30',
    name: 'Jugando Ando',
    logo_url: 'https://images.unsplash.com/photo-1563941402622-4e7a488bcc57?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.79,
    review_count: 43,
    feed_url: 'https://jugandoando.com.mx/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 125,
    feed_last_matched_count: 120,
  },
  {
    id: 'store-kukara-31',
    name: 'Kúkara Games',
    logo_url: 'https://images.unsplash.com/photo-1585504198199-20277593b94f?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.81,
    review_count: 45,
    feed_url: 'https://kukaragames.com/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 130,
    feed_last_matched_count: 125,
  },
  {
    id: 'store-lacasaeducadora-32',
    name: 'La Casa de la Educadora',
    logo_url: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.90,
    review_count: 110,
    feed_url: 'https://lacasadelaeducadora.com/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 350,
    feed_last_matched_count: 340,
  },
  {
    id: 'store-laestanteria-33',
    name: 'La Estantería',
    logo_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.75,
    review_count: 33,
    feed_url: 'https://laestanteria.mx/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 100,
    feed_last_matched_count: 95,
  },
  {
    id: 'store-lamazmorra-34',
    name: 'La Mazmorra',
    logo_url: 'https://images.unsplash.com/photo-1563941402622-4e7a488bcc57?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.87,
    review_count: 61,
    feed_url: 'https://lamazmorra.mx/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 175,
    feed_last_matched_count: 170,
  },
  {
    id: 'store-losnautas-35',
    name: 'Los Nautas',
    logo_url: 'https://images.unsplash.com/photo-1585504198199-20277593b94f?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.77,
    review_count: 38,
    feed_url: 'https://losnautas.com.mx/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 110,
    feed_last_matched_count: 105,
  },
  {
    id: 'store-mandrake-36',
    name: 'Mandrake Juegos',
    logo_url: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.83,
    review_count: 50,
    feed_url: 'https://mandrakejuegos.com/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 145,
    feed_last_matched_count: 140,
  },
  {
    id: 'store-meepleplanet-37',
    name: 'Meeple Planet',
    logo_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.89,
    review_count: 76,
    feed_url: 'https://meepleplanet.mx/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 220,
    feed_last_matched_count: 212,
  },
  {
    id: 'store-montecassino-38',
    name: 'Montecassino',
    logo_url: 'https://images.unsplash.com/photo-1563941402622-4e7a488bcc57?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.76,
    review_count: 34,
    feed_url: 'https://montecassinogames.com/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 100,
    feed_last_matched_count: 95,
  },
  {
    id: 'store-otterspace-39',
    name: 'Otter Space',
    logo_url: 'https://images.unsplash.com/photo-1585504198199-20277593b94f?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.85,
    review_count: 57,
    feed_url: 'https://otterspace.mx/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 165,
    feed_last_matched_count: 160,
  },
  {
    id: 'store-sigad-40',
    name: 'Sigad Juegos',
    logo_url: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.80,
    review_count: 42,
    feed_url: 'https://sigadjuegos.com/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 125,
    feed_last_matched_count: 120,
  },
  {
    id: 'store-tablerazo-41',
    name: 'Tablerazo',
    logo_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.88,
    review_count: 65,
    feed_url: 'https://tablerazo.com.mx/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 185,
    feed_last_matched_count: 180,
  },
  {
    id: 'store-tamandua-42',
    name: 'Tamandúa Juegos',
    logo_url: 'https://images.unsplash.com/photo-1563941402622-4e7a488bcc57?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.78,
    review_count: 36,
    feed_url: 'https://tamanduajuegos.com/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 110,
    feed_last_matched_count: 105,
  },
  {
    id: 'store-tableroninja-43',
    name: 'Tablero Ninja',
    logo_url: 'https://images.unsplash.com/photo-1585504198199-20277593b94f?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.84,
    review_count: 52,
    feed_url: 'https://tableroninja.com/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 155,
    feed_last_matched_count: 150,
  },
  {
    id: 'store-tianguis-44',
    name: 'Tianguis de Juegos',
    logo_url: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.82,
    review_count: 46,
    feed_url: 'https://tianguisdejuegos.com/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 135,
    feed_last_matched_count: 130,
  },
  {
    id: 'store-twist-45',
    name: 'Twist',
    logo_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.73,
    review_count: 30,
    feed_url: 'https://twistjuegos.com/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 90,
    feed_last_matched_count: 85,
  },
  {
    id: 'store-vijoan-46',
    name: 'Vijoan Games',
    logo_url: 'https://images.unsplash.com/photo-1563941402622-4e7a488bcc57?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.86,
    review_count: 59,
    feed_url: 'https://vijoangames.com/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 170,
    feed_last_matched_count: 165,
  },
  {
    id: 'store-vonkraken-47',
    name: 'Vonkraken',
    logo_url: 'https://images.unsplash.com/photo-1585504198199-20277593b94f?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.79,
    review_count: 40,
    feed_url: 'https://vonkraken.com.mx/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 120,
    feed_last_matched_count: 115,
  },
  {
    id: 'store-wontolla-48',
    name: 'Wontolla Games',
    logo_url: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.81,
    review_count: 44,
    feed_url: 'https://wontollagames.com/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 130,
    feed_last_matched_count: 125,
  },
  {
    id: 'store-yego-49',
    name: 'Yego Board Games',
    logo_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.85,
    review_count: 54,
    feed_url: 'https://yegoboardgames.com/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 160,
    feed_last_matched_count: 154,
  },
  {
    id: 'store-yellowrabbit-50',
    name: 'Yellow Rabbit',
    logo_url: 'https://images.unsplash.com/photo-1563941402622-4e7a488bcc57?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.77,
    review_count: 38,
    feed_url: 'https://yellowrabbit.mx/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 110,
    feed_last_matched_count: 105,
  },
  {
    id: 'store-xolotl-51',
    name: 'Xolotl Games',
    logo_url: 'https://images.unsplash.com/photo-1585504198199-20277593b94f?w=120&h=120&fit=crop',
    country: 'MX',
    is_domestic: true,
    rating: 4.83,
    review_count: 48,
    feed_url: 'https://xolotlgames.com/collections/all.atom',
    feed_type: 'google_xml',
    feed_status: 'success',
    feed_last_processed_count: 140,
    feed_last_matched_count: 135,
  },
];

export const INITIAL_SHIPPING_RATES: ShippingRate[] = INITIAL_STORES.map((store, idx) => ({
  store_id: store.id,
  destination_country: 'MX',
  flat_rate: 89.00 + (idx % 5) * 10.00,
  free_shipping_threshold: 999.00 + (idx % 6) * 100.00,
}));

export const INITIAL_BGG_GAMES: BggGame[] = [
  {
    bgg_id: 13,
    name: 'Catan',
    alternate_names: ['The Settlers of Catan', 'Los Descubridores de Catan', 'Catan El Juego'],
    thumbnail: 'https://cf.geekdo-images.com/W3Bs2D0ZaG4vJXZbddeUfw__thumb/img/8a98f3cbef1878d6b1d4023774a350033c46e036/pics/pic2419375.jpg',
    image: 'https://cf.geekdo-images.com/W3Bs2D0ZaG4vJXZbddeUfw__original/img/769f8fa5534c0fb383e9b1191a27e74288b8e018/pics/pic2419375.jpg',
    description: 'En Catan, los jugadores intentan ser el poder dominante en la isla de Catan construyendo asentamientos, ciudades y caminos.',
    weight: 2.30,
    min_players: 3,
    max_players: 4,
    playing_time: 120,
    base_price_eur: 45.00,
    ean: '8435407624108',
    item_type: 'boardgame',
  },
  {
    bgg_id: 382910,
    name: 'Spot It! Catan',
    alternate_names: ['Dobble Catan', 'Spot It Catan Edition'],
    thumbnail: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=300&h=300&fit=crop',
    image: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&h=600&fit=crop',
    description: 'Edición rápida de reconocimiento de patrones Spot It! con símbolos y arte icónico del universo Catan. Juego independiente rápido para toda la familia.',
    weight: 1.05,
    min_players: 2,
    max_players: 8,
    playing_time: 15,
    base_price_eur: 18.00,
    ean: '8435407639102',
    item_type: 'boardgame',
  },
  {
    bgg_id: 926,
    name: 'Catan: Ciudades y Caballeros',
    alternate_names: ['Catan Cities & Knights', 'Catan Ciudades & Caballeros Expansión'],
    thumbnail: 'https://images.unsplash.com/photo-1563941402622-4e7a488bcc57?w=300&h=300&fit=crop',
    image: 'https://images.unsplash.com/photo-1563941402622-4e7a488bcc57?w=800&h=600&fit=crop',
    description: 'Expansión mayor para Catan que añade caballeros, bárbados e infraestructura de desarrollo de ciudades.',
    weight: 2.90,
    min_players: 3,
    max_players: 4,
    playing_time: 150,
    base_price_eur: 42.00,
    ean: '8435407624122',
    item_type: 'expansion',
  },
  {
    bgg_id: 822,
    name: 'Carcassonne',
    alternate_names: ['Carcassonne Base Game'],
    thumbnail: 'https://cf.geekdo-images.com/okj0NB29DFAM94gHkk3cWA__thumb/img/d6df9939e6a00f135b909dfc3e21ec8c4be9ebc2/pics/pic6544250.png',
    image: 'https://cf.geekdo-images.com/okj0NB29DFAM94gHkk3cWA__original/img/d6df9939e6a00f135b909dfc3e21ec8c4be9ebc2/pics/pic6544250.png',
    description: 'Un juego de colocación de losetas donde los jugadores construyen el paisaje alrededor de la fortaleza medieval de Carcassonne.',
    weight: 1.90,
    min_players: 2,
    max_players: 5,
    playing_time: 45,
    base_price_eur: 38.00,
    ean: '8435407621107',
    item_type: 'boardgame',
  },
  {
    bgg_id: 266192,
    name: 'Wingspan',
    alternate_names: ['Wingspan (Español)'],
    thumbnail: 'https://cf.geekdo-images.com/yLZJCVgweBhviWBrTxvMjw__thumb/img/3831868352b2f67645ebff608c028e5785d0d970/pics/pic4458123.jpg',
    image: 'https://cf.geekdo-images.com/yLZJCVgweBhviWBrTxvMjw__original/img/3831868352b2f67645ebff608c028e5785d0d970/pics/pic4458123.jpg',
    description: 'Eres un entusiasta de las aves intentando descubrir y atraer a las mejores aves a tu red de reservas naturales.',
    weight: 2.45,
    min_players: 1,
    max_players: 5,
    playing_time: 70,
    base_price_eur: 60.00,
    ean: '8435407628809',
    item_type: 'boardgame',
  },
  {
    bgg_id: 14996,
    name: 'Ticket to Ride: Europa',
    alternate_names: ['Aventureros al Tren Europa'],
    thumbnail: 'https://cf.geekdo-images.com/kwia39F4s_8-v6e5D9W31A__thumb/img/3ed6f6efb20c5ba53ef7bbfa0ddbc399cb13fbb4/pics/pic6509536.jpg',
    image: 'https://cf.geekdo-images.com/kwia39F4s_8-v6e5D9W31A__original/img/3ed6f6efb20c5ba53ef7bbfa0ddbc399cb13fbb4/pics/pic6509536.jpg',
    description: 'Construye vías de ferrocarril a lo largo de las ciudades clave de la Europa de principios de siglo.',
    weight: 1.92,
    min_players: 2,
    max_players: 5,
    playing_time: 60,
    base_price_eur: 52.00,
    ean: '8435407609204',
    item_type: 'boardgame',
  },
  {
    bgg_id: 230802,
    name: 'Azul',
    alternate_names: ['Azul Base Game'],
    thumbnail: 'https://cf.geekdo-images.com/a97686d11f67f24021d74621fa79e96e__thumb/img/55b3992ae07b22a00c6d7bbca4c478a5796df261/pics/pic3718275.jpg',
    image: 'https://cf.geekdo-images.com/a97686d11f67f24021d74621fa79e96e__original/img/55b3992ae07b22a00c6d7bbca4c478a5796df261/pics/pic3718275.jpg',
    description: 'Decora las paredes del Palacio Real de Évora colocando azulejos de cerámica artesanal.',
    weight: 1.76,
    min_players: 2,
    max_players: 4,
    playing_time: 45,
    base_price_eur: 44.00,
    ean: '8435407619807',
    item_type: 'boardgame',
  },
  {
    bgg_id: 167791,
    name: 'Terraforming Mars',
    alternate_names: ['Terraforming Mars (Español)'],
    thumbnail: 'https://cf.geekdo-images.com/3932822-thumb.jpg',
    image: 'https://cf.geekdo-images.com/3932822-original.jpg',
    description: 'Las corporaciones compiten para transformar Marte en un planeta habitable invirtiendo capital y recursos.',
    weight: 3.25,
    min_players: 1,
    max_players: 5,
    playing_time: 120,
    base_price_eur: 65.00,
    ean: '8435407615007',
    item_type: 'boardgame',
  },
];

export const INITIAL_BARCODES: GameBarcode[] = [
  { id: 'gb-01', barcode: '8435407624108', bgg_id: 13, edition_language: 'es', publisher_name: 'Devir' },
  { id: 'gb-02', barcode: '8435407639102', bgg_id: 382910, edition_language: 'es', publisher_name: 'Zygomatic' },
  { id: 'gb-03', barcode: '8435407624122', bgg_id: 926, edition_language: 'es', publisher_name: 'Devir' },
  { id: 'gb-04', barcode: '8435407621107', bgg_id: 822, edition_language: 'es', publisher_name: 'Devir' },
  { id: 'gb-05', barcode: '8435407628809', bgg_id: 266192, edition_language: 'es', publisher_name: 'Maldito Games' },
  { id: 'gb-06', barcode: '8435407609204', bgg_id: 14996, edition_language: 'es', publisher_name: 'Days of Wonder' },
  { id: 'gb-07', barcode: '8435407619807', bgg_id: 230802, edition_language: 'es', publisher_name: 'Asmodee' },
  { id: 'gb-08', barcode: '8435407615007', bgg_id: 167791, edition_language: 'es', publisher_name: 'Maldito Games' },
];

export const INITIAL_MAPPINGS: MerchantProductMapping[] = [
  { id: 'mpm-01', store_id: 'store-ficha-01', merchant_sku: 'DEV-CATAN-ES', bgg_id: 13, is_verified: true },
  { id: 'mpm-02', store_id: 'store-mundomeeple-02', merchant_sku: 'CATAN-BASE-MX', bgg_id: 13, is_verified: true },
  { id: 'mpm-03', store_id: 'store-rollgames-03', merchant_sku: 'SPOT-IT-CATAN', bgg_id: 382910, is_verified: true },
];

export const INITIAL_OFFERS: StoreGameOffer[] = [
  {
    id: 'offer-01',
    store_id: 'store-ficha-01',
    bgg_id: 13,
    store_product_url: 'https://fichaydado.com/products/catan-juego-de-mesa',
    price: 949.00,
    stock: 12,
    edition_language: 'es',
    is_featured: true,
    match_confidence: 1.00,
    match_tier: 1,
  },
  {
    id: 'offer-02',
    store_id: 'store-mundomeeple-02',
    bgg_id: 13,
    store_product_url: 'https://mundomeeplestore.com/products/catan-edicion-espanol',
    price: 899.00,
    stock: 5,
    edition_language: 'es',
    is_featured: false,
    match_confidence: 1.00,
    match_tier: 2,
  },
  {
    id: 'offer-03',
    store_id: 'store-rollgames-03',
    bgg_id: 13,
    store_product_url: 'https://rollgames.mx/products/catan',
    price: 980.00,
    stock: 3,
    edition_language: 'en',
    is_featured: false,
    match_confidence: 0.95,
    match_tier: 3,
  },
  {
    id: 'offer-04',
    store_id: 'store-quantum-05',
    bgg_id: 13,
    store_product_url: 'https://quantumboardgames.com/products/catan-espanol',
    price: 920.00,
    stock: 8,
    edition_language: 'es',
    is_featured: false,
    match_confidence: 1.00,
    match_tier: 1,
  },
  {
    id: 'offer-05',
    store_id: 'store-geekystuff-08',
    bgg_id: 13,
    store_product_url: 'https://geekystuff.com.mx/products/catan',
    price: 935.00,
    stock: 10,
    edition_language: 'es',
    is_featured: false,
    match_confidence: 1.00,
    match_tier: 1,
  },
  {
    id: 'offer-06',
    store_id: 'store-rollgames-03',
    bgg_id: 382910,
    store_product_url: 'https://rollgames.mx/products/spot-it-catan',
    price: 380.00,
    stock: 15,
    edition_language: 'es',
    is_featured: false,
    match_confidence: 1.00,
    match_tier: 1,
  },
  {
    id: 'offer-07',
    store_id: 'store-ficha-01',
    bgg_id: 926,
    store_product_url: 'https://fichaydado.com/products/catan-ciudades-y-caballeros',
    price: 850.00,
    stock: 4,
    edition_language: 'es',
    is_featured: false,
    match_confidence: 1.00,
    match_tier: 1,
  },
  {
    id: 'offer-08',
    store_id: 'store-mundomeeple-02',
    bgg_id: 822,
    store_product_url: 'https://mundomeeplestore.com/products/carcassonne',
    price: 799.00,
    stock: 10,
    edition_language: 'es',
    is_featured: false,
    match_confidence: 1.00,
    match_tier: 1,
  },
  {
    id: 'offer-09',
    store_id: 'store-quantum-05',
    bgg_id: 266192,
    store_product_url: 'https://quantumboardgames.com/products/wingspan',
    price: 1299.00,
    stock: 6,
    edition_language: 'es',
    is_featured: true,
    match_confidence: 1.00,
    match_tier: 1,
  },
];

export const INITIAL_QUEUE_ITEMS: QueueItem[] = [
  {
    id: 'queue-01',
    store_id: 'store-mundomeeple-02',
    ean: '8435407639999',
    title: 'Catan Edición 3D Coleccionista (Preventa)',
    store_product_url: 'https://mundomeeplestore.com/products/catan-3d-collector',
    status: 'pending',
    match_confidence: 0.82,
    suggested_bgg_id: 13,
  },
  {
    id: 'queue-02',
    store_id: 'store-ficha-01',
    ean: '8435407641111',
    title: 'Munchkin Catan Crossover Pack',
    store_product_url: 'https://fichaydado.com/products/munchkin-catan',
    status: 'pending',
    match_confidence: 0.75,
    suggested_bgg_id: 13,
  },
];
