import { Store, ShippingRate, BggGame, GameBarcode, MerchantProductMapping, StoreGameOffer, QueueItem } from '@/types';

export const INITIAL_STORES: Store[] = [
  {
    "id": "store-ficha-01",
    "name": "Ficha y Dado",
    "logo_url": "https://www.google.com/s2/favicons?domain=fichaydado.com&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.9,
    "review_count": 128,
    "feed_url": "https://fichaydado.com/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 420,
    "feed_last_matched_count": 412
  },
  {
    "id": "store-mundomeeple-02",
    "name": "Mundo Meeple Store",
    "logo_url": "https://www.google.com/s2/favicons?domain=mundomeeplestore.com&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.85,
    "review_count": 95,
    "feed_url": "https://mundomeeplestore.com/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 310,
    "feed_last_matched_count": 305
  },
  {
    "id": "store-rollgames-03",
    "name": "Roll Games",
    "logo_url": "https://www.google.com/s2/favicons?domain=rollgames.mx&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.75,
    "review_count": 64,
    "feed_url": "https://rollgames.mx/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 180,
    "feed_last_matched_count": 175
  },
  {
    "id": "store-tlacuache-04",
    "name": "Con T de Tlacuache",
    "logo_url": "https://www.google.com/s2/favicons?domain=tdetlacuache.com&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.88,
    "review_count": 72,
    "feed_url": "https://tdetlacuache.com/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 210,
    "feed_last_matched_count": 204
  },
  {
    "id": "store-quantum-05",
    "name": "Quantum Boardgames",
    "logo_url": "https://www.google.com/s2/favicons?domain=quantumboardgames.com&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.92,
    "review_count": 88,
    "feed_url": "https://quantumboardgames.com/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 250,
    "feed_last_matched_count": 242
  },
  {
    "id": "store-alfaydelta-06",
    "name": "Alfa y Delta",
    "logo_url": "https://alfaydelta.com/cdn/shop/files/Logo_RGB_corregido.png?crop=center&height=128&v=1687398586&width=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.8,
    "review_count": 52,
    "feed_url": "https://alfaydelta.com/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 160,
    "feed_last_matched_count": 155
  },
  {
    "id": "store-bundaba-07",
    "name": "Bundaba",
    "logo_url": "https://bundaba.com.mx/cdn/shop/files/Bee_Icon_6aca720a-1649-4bbe-8938-90923ed7644a.png?v=1736432118&width=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.82,
    "review_count": 46,
    "feed_url": "https://bundaba.com.mx/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 140,
    "feed_last_matched_count": 135
  },
  {
    "id": "store-geekystuff-08",
    "name": "Geeky Stuff",
    "logo_url": "https://www.google.com/s2/favicons?domain=geekystuff.com.mx&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.86,
    "review_count": 68,
    "feed_url": "https://geekystuff.com.mx/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 195,
    "feed_last_matched_count": 188
  },
  {
    "id": "store-2tomatoes-09",
    "name": "2 Tomatoes MX",
    "logo_url": "https://www.google.com/s2/favicons?domain=2tomatoesgames.com.mx&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.79,
    "review_count": 42,
    "feed_url": "https://2tomatoesgames.com.mx/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 120,
    "feed_last_matched_count": 115
  },
  {
    "id": "store-amukiri-10",
    "name": "Amukiri",
    "logo_url": "https://www.google.com/s2/favicons?domain=amukiri.com.mx&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.7,
    "review_count": 35,
    "feed_url": "https://amukiri.com.mx/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 95,
    "feed_last_matched_count": 90
  },
  {
    "id": "store-avalon-11",
    "name": "Avalon Store",
    "logo_url": "https://www.google.com/s2/favicons?domain=avalonstore.mx&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.84,
    "review_count": 58,
    "feed_url": "https://avalonstore.mx/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 175,
    "feed_last_matched_count": 170
  },
  {
    "id": "store-cabala-12",
    "name": "Cábala Games",
    "logo_url": "https://www.google.com/s2/favicons?domain=cabalagames.mx&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.77,
    "review_count": 39,
    "feed_url": "https://cabalagames.mx/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 110,
    "feed_last_matched_count": 106
  },
  {
    "id": "store-catito-13",
    "name": "Catito Games",
    "logo_url": "https://www.google.com/s2/favicons?domain=catitogames.com&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.89,
    "review_count": 63,
    "feed_url": "https://catitogames.com/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 185,
    "feed_last_matched_count": 180
  },
  {
    "id": "store-chocita-14",
    "name": "Chocita Juegos",
    "logo_url": "https://chocitajuegos.com/wp-content/uploads/2026/01/cropped-Chochita-Juegos-Imagotipo-32x32.png",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.81,
    "review_count": 47,
    "feed_url": "https://chocitajuegos.com/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 150,
    "feed_last_matched_count": 144
  },
  {
    "id": "store-demon-15",
    "name": "Demon Juegos",
    "logo_url": "https://www.google.com/s2/favicons?domain=demonjuegos.com&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.78,
    "review_count": 41,
    "feed_url": "https://demonjuegos.com/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 130,
    "feed_last_matched_count": 126
  },
  {
    "id": "store-diad-16",
    "name": "Día D Juegos",
    "logo_url": "https://www.google.com/s2/favicons?domain=diadjuegos.com&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.91,
    "review_count": 83,
    "feed_url": "https://diadjuegos.com/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 240,
    "feed_last_matched_count": 232
  },
  {
    "id": "store-eramu-17",
    "name": "Eramu Juegos y Café",
    "logo_url": "https://www.google.com/s2/favicons?domain=eramujuegos.com&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.74,
    "review_count": 31,
    "feed_url": "https://eramujuegos.com/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 90,
    "feed_last_matched_count": 86
  },
  {
    "id": "store-eximia-18",
    "name": "Eximia Games",
    "logo_url": "https://www.google.com/s2/favicons?domain=eximiagames.com&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.87,
    "review_count": 55,
    "feed_url": "https://eximiagames.com/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 165,
    "feed_last_matched_count": 160
  },
  {
    "id": "store-gamesmart-19",
    "name": "GameSmart",
    "logo_url": "https://www.google.com/s2/favicons?domain=gamesmart.com.mx&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.83,
    "review_count": 49,
    "feed_url": "https://gamesmart.com.mx/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 145,
    "feed_last_matched_count": 140
  },
  {
    "id": "store-geim-20",
    "name": "Geim Puebla",
    "logo_url": "https://www.google.com/s2/favicons?domain=geimpuebla.com&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.76,
    "review_count": 36,
    "feed_url": "https://geimpuebla.com/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 105,
    "feed_last_matched_count": 100
  },
  {
    "id": "store-hobbiton-21",
    "name": "Hobbiton Games",
    "logo_url": "https://www.google.com/s2/favicons?domain=hobbitongames.com&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.93,
    "review_count": 91,
    "feed_url": "https://hobbitongames.com/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 270,
    "feed_last_matched_count": 264
  },
  {
    "id": "store-hobbyguild-22",
    "name": "Hobby Guild",
    "logo_url": "https://hobbyguild.mx/cdn/shop/files/Hobby_Guild_Logo_-_Sin_fondo.png?crop=center&height=128&v=1754515684&width=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.8,
    "review_count": 44,
    "feed_url": "https://hobbyguild.mx/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 135,
    "feed_last_matched_count": 130
  },
  {
    "id": "store-imperio-23",
    "name": "Imperio Games",
    "logo_url": "https://www.google.com/s2/favicons?domain=imperiogames.com.mx&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.85,
    "review_count": 53,
    "feed_url": "https://imperiogames.com.mx/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 155,
    "feed_last_matched_count": 150
  },
  {
    "id": "store-ingenioz-24",
    "name": "Ingenioz",
    "logo_url": "https://ingenioz.com.mx/web/image/website/1/dr_pwa_icon_192/192x192",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.72,
    "review_count": 29,
    "feed_url": "https://ingenioz.com.mx/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 85,
    "feed_last_matched_count": 80
  },
  {
    "id": "store-juegamas-25",
    "name": "Juega Más",
    "logo_url": "https://www.google.com/s2/favicons?domain=juegamas.com.mx&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.82,
    "review_count": 48,
    "feed_url": "https://juegamas.com.mx/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 140,
    "feed_last_matched_count": 135
  },
  {
    "id": "store-juegateeste-26",
    "name": "Juégate Este",
    "logo_url": "https://www.google.com/s2/favicons?domain=juegateeste.com&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.78,
    "review_count": 37,
    "feed_url": "https://juegateeste.com/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 115,
    "feed_last_matched_count": 110
  },
  {
    "id": "store-belugas-27",
    "name": "Juego de Belugas",
    "logo_url": "https://www.google.com/s2/favicons?domain=juedodebelugas.com&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.84,
    "review_count": 51,
    "feed_url": "https://juedodebelugas.com/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 150,
    "feed_last_matched_count": 145
  },
  {
    "id": "store-patolli-28",
    "name": "Juegos Patolli",
    "logo_url": "https://www.google.com/s2/favicons?domain=juegospatolli.com&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.88,
    "review_count": 67,
    "feed_url": "https://juegospatolli.com/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 190,
    "feed_last_matched_count": 184
  },
  {
    "id": "store-jugadorinicial-29",
    "name": "Jugador Inicial",
    "logo_url": "https://jugadorinicial.com.mx/cdn/shop/files/carro-de-la-carretilla_32x32.png?v=1663629888",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.86,
    "review_count": 59,
    "feed_url": "https://jugadorinicial.com.mx/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 170,
    "feed_last_matched_count": 165
  },
  {
    "id": "store-jugandoando-30",
    "name": "Jugando Ando",
    "logo_url": "https://jugandoando.com/cdn/shop/files/favicon-32x32_32x32.png?v=1756066294",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.79,
    "review_count": 43,
    "feed_url": "https://jugandoando.com.mx/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 125,
    "feed_last_matched_count": 120
  },
  {
    "id": "store-kukara-31",
    "name": "Kúkara Games",
    "logo_url": "https://www.kukaragames.com/cdn/shop/files/kukara_2_1_e3a01441-b4d1-4586-b70f-27f0d3476d46.png?crop=center&height=128&v=1644378844&width=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.81,
    "review_count": 45,
    "feed_url": "https://kukaragames.com/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 130,
    "feed_last_matched_count": 125
  },
  {
    "id": "store-lacasaeducadora-32",
    "name": "La Casa de la Educadora",
    "logo_url": "https://lacasadelaeducadora.com/cdn/shop/files/LOGO_lacasa_cuadrado_marco_96x96.png?v=1684878102",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.9,
    "review_count": 110,
    "feed_url": "https://lacasadelaeducadora.com/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 350,
    "feed_last_matched_count": 340
  },
  {
    "id": "store-laestanteria-33",
    "name": "La Estantería",
    "logo_url": "https://www.google.com/s2/favicons?domain=laestanteria.mx&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.75,
    "review_count": 33,
    "feed_url": "https://laestanteria.mx/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 100,
    "feed_last_matched_count": 95
  },
  {
    "id": "store-lamazmorra-34",
    "name": "La Mazmorra",
    "logo_url": "https://www.lamazmorra.mx/cdn/shop/files/fav-maz-2_32x32.png?v=1687999718",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.87,
    "review_count": 61,
    "feed_url": "https://lamazmorra.mx/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 175,
    "feed_last_matched_count": 170
  },
  {
    "id": "store-losnautas-35",
    "name": "Los Nautas",
    "logo_url": "https://www.google.com/s2/favicons?domain=losnautas.com.mx&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.77,
    "review_count": 38,
    "feed_url": "https://losnautas.com.mx/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 110,
    "feed_last_matched_count": 105
  },
  {
    "id": "store-mandrake-36",
    "name": "Mandrake Juegos",
    "logo_url": "https://mandrakejuegos.com/cdn/shop/files/AJUSTADO_FONDO_T.png?crop=center&height=128&v=1742750924&width=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.83,
    "review_count": 50,
    "feed_url": "https://mandrakejuegos.com/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 145,
    "feed_last_matched_count": 140
  },
  {
    "id": "store-meepleplanet-37",
    "name": "Meeple Planet",
    "logo_url": "https://www.google.com/s2/favicons?domain=meepleplanet.mx&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.89,
    "review_count": 76,
    "feed_url": "https://meepleplanet.mx/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 220,
    "feed_last_matched_count": 212
  },
  {
    "id": "store-montecassino-38",
    "name": "Montecassino",
    "logo_url": "https://www.google.com/s2/favicons?domain=montecassinogames.com&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.76,
    "review_count": 34,
    "feed_url": "https://montecassinogames.com/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 100,
    "feed_last_matched_count": 95
  },
  {
    "id": "store-otterspace-39",
    "name": "Otter Space",
    "logo_url": "https://www.google.com/s2/favicons?domain=otterspace.mx&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.85,
    "review_count": 57,
    "feed_url": "https://otterspace.mx/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 165,
    "feed_last_matched_count": 160
  },
  {
    "id": "store-sigad-40",
    "name": "Sigad Juegos",
    "logo_url": "https://www.google.com/s2/favicons?domain=sigadjuegos.com&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.8,
    "review_count": 42,
    "feed_url": "https://sigadjuegos.com/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 125,
    "feed_last_matched_count": 120
  },
  {
    "id": "store-tablerazo-41",
    "name": "Tablerazo",
    "logo_url": "https://www.google.com/s2/favicons?domain=tablerazo.com.mx&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.88,
    "review_count": 65,
    "feed_url": "https://tablerazo.com.mx/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 185,
    "feed_last_matched_count": 180
  },
  {
    "id": "store-tamandua-42",
    "name": "Tamandúa Juegos",
    "logo_url": "https://tamanduajuegos.com/wp-content/uploads/2023/08/cropped-favicon-tamandua-juegos-32x32.png",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.78,
    "review_count": 36,
    "feed_url": "https://tamanduajuegos.com/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 110,
    "feed_last_matched_count": 105
  },
  {
    "id": "store-tableroninja-43",
    "name": "Tablero Ninja",
    "logo_url": "https://static.wixstatic.com/media/adfd83_89c74e2f551647f8a57efe42ecfa3c78%7Emv2.png/v1/fill/w_192%2Ch_192%2Clg_1%2Cusm_0.66_1.00_0.01/adfd83_89c74e2f551647f8a57efe42ecfa3c78%7Emv2.png",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.84,
    "review_count": 52,
    "feed_url": "https://tableroninja.com/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 155,
    "feed_last_matched_count": 150
  },
  {
    "id": "store-tianguis-44",
    "name": "Tianguis de Juegos",
    "logo_url": "https://www.google.com/s2/favicons?domain=tianguisdejuegos.com&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.82,
    "review_count": 46,
    "feed_url": "https://tianguisdejuegos.com/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 135,
    "feed_last_matched_count": 130
  },
  {
    "id": "store-twist-45",
    "name": "Twist",
    "logo_url": "https://www.google.com/s2/favicons?domain=twistjuegos.com&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.73,
    "review_count": 30,
    "feed_url": "https://twistjuegos.com/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 90,
    "feed_last_matched_count": 85
  },
  {
    "id": "store-vijoan-46",
    "name": "Vijoan Games",
    "logo_url": "https://vijoangames.com/cdn/shop/files/Vijoan_favicon_32x32.png?v=1715969599",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.86,
    "review_count": 59,
    "feed_url": "https://vijoangames.com/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 170,
    "feed_last_matched_count": 165
  },
  {
    "id": "store-vonkraken-47",
    "name": "Vonkraken",
    "logo_url": "https://www.google.com/s2/favicons?domain=vonkraken.com.mx&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.79,
    "review_count": 40,
    "feed_url": "https://vonkraken.com.mx/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 120,
    "feed_last_matched_count": 115
  },
  {
    "id": "store-wontolla-48",
    "name": "Wontolla Games",
    "logo_url": "https://static.wixstatic.com/media/c00b37_62c98c1022ae47f8a816e1e974ba560e%7Emv2.jpeg/v1/fill/w_192%2Ch_192%2Clg_1%2Cusm_0.66_1.00_0.01/c00b37_62c98c1022ae47f8a816e1e974ba560e%7Emv2.jpeg",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.81,
    "review_count": 44,
    "feed_url": "https://wontollagames.com/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 130,
    "feed_last_matched_count": 125
  },
  {
    "id": "store-yego-49",
    "name": "Yego Board Games",
    "logo_url": "https://www.google.com/s2/favicons?domain=yegoboardgames.com&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.85,
    "review_count": 54,
    "feed_url": "https://yegoboardgames.com/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 160,
    "feed_last_matched_count": 154
  },
  {
    "id": "store-yellowrabbit-50",
    "name": "Yellow Rabbit",
    "logo_url": "https://yellowrabbit.mx/cdn/shop/files/Mesa_de_trabajo_10_32x32.png?v=1730853258",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.77,
    "review_count": 38,
    "feed_url": "https://yellowrabbit.mx/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 110,
    "feed_last_matched_count": 105
  },
  {
    "id": "store-xolotl-51",
    "name": "Xolotl Games",
    "logo_url": "https://www.google.com/s2/favicons?domain=xolotlgames.com&sz=128",
    "country": "MX",
    "is_domestic": true,
    "rating": 4.83,
    "review_count": 48,
    "feed_url": "https://xolotlgames.com/collections/all.atom",
    "feed_type": "google_xml",
    "feed_status": "success",
    "feed_last_processed_count": 140,
    "feed_last_matched_count": 135
  }
];

export const INITIAL_SHIPPING_RATES: ShippingRate[] = INITIAL_STORES.map((store, idx) => ({
  store_id: store.id,
  destination_country: 'MX',
  flat_rate: 89.00 + (idx % 5) * 10.00,
  free_shipping_threshold: 999.00 + (idx % 6) * 100.00,
}));

export const INITIAL_BGG_GAMES: BggGame[] = [
  {
    bgg_id: 224517,
    name: 'Brass: Birmingham',
    alternate_names: ['Brass Birmingham'],
    thumbnail: 'https://cf.geekdo-images.com/x3zxjrcaVpBqEY23yb4A6A__thumb/img/o1y3yB24x72365287.jpg',
    image: 'https://cf.geekdo-images.com/x3zxjrcaVpBqEY23yb4A6A__original/img/o1y3yB24x72365287.jpg',
    description: 'Construye tu imperio industrial compitiendo por canales, ferrocarriles e industrias en la Revolución Industrial.',
    weight: 3.91,
    min_players: 2,
    max_players: 4,
    playing_time: 120,
    base_price_eur: 85.00,
    bgg_rank: 1,
    search_count: 3420,
    item_type: 'boardgame',
  },
  {
    bgg_id: 161936,
    name: 'Pandemic Legacy: Season 1',
    alternate_names: ['Pandemic Legacy Temporada 1'],
    thumbnail: 'https://cf.geekdo-images.com/q3-w2417772.jpg',
    image: 'https://cf.geekdo-images.com/q3-w2417772.jpg',
    description: 'Salva al mundo en una campaña cooperativa episódica de 12 meses donde cada decisión altera el mapa permanentemente.',
    weight: 2.83,
    min_players: 2,
    max_players: 4,
    playing_time: 60,
    base_price_eur: 75.00,
    bgg_rank: 2,
    search_count: 2150,
    item_type: 'boardgame',
  },
  {
    bgg_id: 342942,
    name: 'Ark Nova',
    alternate_names: ['Ark Nova (Español)'],
    thumbnail: 'https://cf.geekdo-images.com/wqGjA9t2477810.jpg',
    image: 'https://cf.geekdo-images.com/wqGjA9t2477810.jpg',
    description: 'Diseña y gestiona un zoológico moderno orientado a la conservación de especies y la investigación científica.',
    weight: 3.74,
    min_players: 1,
    max_players: 4,
    playing_time: 150,
    base_price_eur: 70.00,
    bgg_rank: 3,
    search_count: 4100,
    item_type: 'boardgame',
  },
  {
    bgg_id: 174430,
    name: 'Gloomhaven',
    alternate_names: ['Gloomhaven (Español)'],
    thumbnail: 'https://cf.geekdo-images.com/sZY2537482.jpg',
    image: 'https://cf.geekdo-images.com/sZY2537482.jpg',
    description: 'Un juego de combate táctico cooperativo en un mundo de fantasía oscura con toma de decisiones persistente.',
    weight: 3.90,
    min_players: 1,
    max_players: 4,
    playing_time: 120,
    base_price_eur: 140.00,
    bgg_rank: 4,
    search_count: 2890,
    item_type: 'boardgame',
  },
  {
    bgg_id: 316554,
    name: 'Dune: Imperium',
    alternate_names: ['Dune Imperium (Español)'],
    thumbnail: 'https://cf.geekdo-images.com/WDqkA853381.jpg',
    image: 'https://cf.geekdo-images.com/WDqkA853381.jpg',
    description: 'Combina construcción de mazos y colocación de trabajadores para dominar la especia en el desértico Arrakis.',
    weight: 3.05,
    min_players: 1,
    max_players: 4,
    playing_time: 120,
    base_price_eur: 55.00,
    bgg_rank: 5,
    search_count: 4850,
    item_type: 'boardgame',
  },
  {
    bgg_id: 167791,
    name: 'Terraforming Mars',
    alternate_names: ['Terraforming Mars (Español)'],
    thumbnail: 'https://cf.geekdo-images.com/3932822-thumb.jpg',
    image: 'https://cf.geekdo-images.com/3932822-original.jpg',
    description: 'Las corporaciones compiten para transformar Marte en un planeta habitable invirtiendo capital y recursos.',
    weight: 3.25,
    min_players: 1,
    max_players: 5,
    playing_time: 120,
    base_price_eur: 65.00,
    bgg_rank: 6,
    search_count: 5200,
    ean: '8435407615007',
    item_type: 'boardgame',
  },
  {
    bgg_id: 266192,
    name: 'Wingspan',
    alternate_names: ['Wingspan (Español)'],
    thumbnail: 'https://cf.geekdo-images.com/yLZJCVgweBhviWBrTxvMjw__thumb/img/3831868352b2f67645ebff608c028e5785d0d970/pics/pic4458123.jpg',
    image: 'https://cf.geekdo-images.com/yLZJCVgweBhviWBrTxvMjw__original/img/3831868352b2f67645ebff608c028e5785d0d970/pics/pic4458123.jpg',
    description: 'Eres un entusiasta de las aves intentando descubrir y atraer a las mejores aves a tu red de reservas naturales.',
    weight: 2.45,
    min_players: 1,
    max_players: 5,
    playing_time: 70,
    base_price_eur: 60.00,
    bgg_rank: 7,
    search_count: 6120,
    ean: '8435407628809',
    item_type: 'boardgame',
  },
  {
    bgg_id: 230802,
    name: 'Azul',
    alternate_names: ['Azul Base Game'],
    thumbnail: 'https://cf.geekdo-images.com/a97686d11f67f24021d74621fa79e96e__thumb/img/55b3992ae07b22a00c6d7bbca4c478a5796df261/pics/pic3718275.jpg',
    image: 'https://cf.geekdo-images.com/a97686d11f67f24021d74621fa79e96e__original/img/55b3992ae07b22a00c6d7bbca4c478a5796df261/pics/pic3718275.jpg',
    description: 'Decora las paredes del Palacio Real de Évora colocando azulejos de cerámica artesanal.',
    weight: 1.76,
    min_players: 2,
    max_players: 4,
    playing_time: 45,
    base_price_eur: 44.00,
    bgg_rank: 8,
    search_count: 4780,
    ean: '8435407619807',
    item_type: 'boardgame',
  },
  {
    bgg_id: 13,
    name: 'Catan',
    alternate_names: ['The Settlers of Catan', 'Los Descubridores de Catan', 'Catan El Juego'],
    thumbnail: 'https://cf.geekdo-images.com/W3Bs2D0ZaG4vJXZbddeUfw__thumb/img/8a98f3cbef1878d6b1d4023774a350033c46e036/pics/pic2419375.jpg',
    image: 'https://cf.geekdo-images.com/W3Bs2D0ZaG4vJXZbddeUfw__original/img/769f8fa5534c0fb383e9b1191a27e74288b8e018/pics/pic2419375.jpg',
    description: 'En Catan, los jugadores intentan ser el poder dominante en la isla de Catan construyendo asentamientos, ciudades y caminos.',
    weight: 2.30,
    min_players: 3,
    max_players: 4,
    playing_time: 120,
    base_price_eur: 45.00,
    bgg_rank: 9,
    search_count: 9850,
    ean: '8435407624108',
    item_type: 'boardgame',
  },
  {
    bgg_id: 822,
    name: 'Carcassonne',
    alternate_names: ['Carcassonne Base Game'],
    thumbnail: 'https://cf.geekdo-images.com/okj0NB29DFAM94gHkk3cWA__thumb/img/d6df9939e6a00f135b909dfc3e21ec8c4be9ebc2/pics/pic6544250.png',
    image: 'https://cf.geekdo-images.com/okj0NB29DFAM94gHkk3cWA__original/img/d6df9939e6a00f135b909dfc3e21ec8c4be9ebc2/pics/pic6544250.png',
    description: 'Un juego de colocación de losetas donde los jugadores construyen el paisaje alrededor de la fortaleza medieval de Carcassonne.',
    weight: 1.90,
    min_players: 2,
    max_players: 5,
    playing_time: 45,
    base_price_eur: 38.00,
    bgg_rank: 10,
    search_count: 5400,
    ean: '8435407621107',
    item_type: 'boardgame',
  },
  {
    bgg_id: 14996,
    name: 'Ticket to Ride: Europa',
    alternate_names: ['Aventureros al Tren Europa'],
    thumbnail: 'https://cf.geekdo-images.com/kwia39F4s_8-v6e5D9W31A__thumb/img/3ed6f6efb20c5ba53ef7bbfa0ddbc399cb13fbb4/pics/pic6509536.jpg',
    image: 'https://cf.geekdo-images.com/kwia39F4s_8-v6e5D9W31A__original/img/3ed6f6efb20c5ba53ef7bbfa0ddbc399cb13fbb4/pics/pic6509536.jpg',
    description: 'Construye vías de ferrocarril a lo largo de las ciudades clave de la Europa de principios de siglo.',
    weight: 1.92,
    min_players: 2,
    max_players: 5,
    playing_time: 60,
    base_price_eur: 52.00,
    bgg_rank: 15,
    search_count: 4300,
    ean: '8435407609204',
    item_type: 'boardgame',
  },
  {
    bgg_id: 926,
    name: 'Catan: Ciudades y Caballeros',
    alternate_names: ['Catan Cities & Knights', 'Catan Ciudades & Caballeros Expansión'],
    thumbnail: 'https://images.unsplash.com/photo-1563941402622-4e7a488bcc57?w=300&h=300&fit=crop',
    image: 'https://images.unsplash.com/photo-1563941402622-4e7a488bcc57?w=800&h=600&fit=crop',
    description: 'Expansión mayor para Catan que añade caballeros, bárbados e infraestructura de desarrollo de ciudades.',
    weight: 2.90,
    min_players: 3,
    max_players: 4,
    playing_time: 150,
    base_price_eur: 42.00,
    bgg_rank: 42,
    search_count: 2100,
    ean: '8435407624122',
    item_type: 'expansion',
  },
  {
    bgg_id: 173346,
    name: '7 Wonders Duel',
    alternate_names: ['7 Wonders Duel (Español)'],
    thumbnail: 'https://cf.geekdo-images.com/W3Bs2D0ZaG4vJXZbddeUfw__thumb/img/8a98f3cbef1878d6b1d4023774a350033c46e036/pics/pic2419375.jpg',
    image: 'https://cf.geekdo-images.com/W3Bs2D0ZaG4vJXZbddeUfw__original/img/769f8fa5534c0fb383e9b1191a27e74288b8e018/pics/pic2419375.jpg',
    description: 'Enfréntate cara a cara en una civilización de 3 eras adaptada especialmente para 2 jugadores.',
    weight: 2.23,
    min_players: 2,
    max_players: 2,
    playing_time: 30,
    base_price_eur: 32.00,
    bgg_rank: 18,
    search_count: 5100,
    item_type: 'boardgame',
  },
  {
    bgg_id: 148228,
    name: 'Splendor',
    alternate_names: ['Splendor (Español)'],
    thumbnail: 'https://cf.geekdo-images.com/v8hTrBq3B7Vw52.jpg',
    image: 'https://cf.geekdo-images.com/v8hTrBq3B7Vw52.jpg',
    description: 'Como un rico mercader del Renacimiento, adquiere minas, medios de transporte y artesanos para acumular puntos de prestigio.',
    weight: 1.79,
    min_players: 2,
    max_players: 4,
    playing_time: 30,
    base_price_eur: 38.00,
    bgg_rank: 72,
    search_count: 7200,
    item_type: 'boardgame',
  },
  {
    bgg_id: 295947,
    name: 'Cascadia',
    alternate_names: ['Cascadia (Español)'],
    thumbnail: 'https://cf.geekdo-images.com/Cascadia.jpg',
    image: 'https://cf.geekdo-images.com/Cascadia.jpg',
    description: 'Crea tu propio ecosistema del Pacífico Noroeste colocando losetas de hábitat y fichas de fauna salvaje.',
    weight: 1.84,
    min_players: 1,
    max_players: 4,
    playing_time: 45,
    base_price_eur: 42.00,
    bgg_rank: 48,
    search_count: 4500,
    item_type: 'boardgame',
  },
  {
    bgg_id: 30549,
    name: 'Pandemic',
    alternate_names: ['Pandemia'],
    thumbnail: 'https://cf.geekdo-images.com/Pandemic.jpg',
    image: 'https://cf.geekdo-images.com/Pandemic.jpg',
    description: 'Trabajen juntos como miembros de un equipo especializado en contención de enfermedades para curar 4 plagas mortales.',
    weight: 2.40,
    min_players: 2,
    max_players: 4,
    playing_time: 45,
    base_price_eur: 40.00,
    bgg_rank: 110,
    search_count: 8900,
    item_type: 'boardgame',
  },
  {
    bgg_id: 169786,
    name: 'Scythe',
    alternate_names: ['Scythe (Español)'],
    thumbnail: 'https://cf.geekdo-images.com/Scythe.jpg',
    image: 'https://cf.geekdo-images.com/Scythe.jpg',
    description: 'Guía a tu facción hacia la victoria en una historia alternativa de los años 1920 con mechas de combate y control territorial.',
    weight: 3.44,
    min_players: 1,
    max_players: 5,
    playing_time: 115,
    base_price_eur: 80.00,
    bgg_rank: 16,
    search_count: 3900,
    item_type: 'boardgame',
  },
  {
    bgg_id: 237182,
    name: 'Root',
    alternate_names: ['Root (Español)'],
    thumbnail: 'https://cf.geekdo-images.com/Root.jpg',
    image: 'https://cf.geekdo-images.com/Root.jpg',
    description: 'Un juego asimétrico de poder y guerra en un bosque habitado por criaturas fantásticas compitiendo por el control.',
    weight: 3.79,
    min_players: 2,
    max_players: 4,
    playing_time: 90,
    base_price_eur: 65.00,
    bgg_rank: 28,
    search_count: 4600,
    item_type: 'boardgame',
  },
  {
    bgg_id: 251247,
    name: 'Everdell',
    alternate_names: ['Everdell (Español)'],
    thumbnail: 'https://cf.geekdo-images.com/Everdell.jpg',
    image: 'https://cf.geekdo-images.com/Everdell.jpg',
    description: 'Lidera a un grupo de criaturas del bosque para construir una floreciente ciudad bajo las ramas del Gran Árbol.',
    weight: 2.82,
    min_players: 1,
    max_players: 4,
    playing_time: 80,
    base_price_eur: 60.00,
    bgg_rank: 34,
    search_count: 5300,
    item_type: 'boardgame',
  },
  {
    bgg_id: 39856,
    name: 'Dixit',
    alternate_names: ['Dixit (Español)'],
    thumbnail: 'https://cf.geekdo-images.com/Dixit.jpg',
    image: 'https://cf.geekdo-images.com/Dixit.jpg',
    description: 'Un juego de cartas ilustradas de deducción de pistas e imaginación para compartir con amigos y familia.',
    weight: 1.22,
    min_players: 3,
    max_players: 8,
    playing_time: 30,
    base_price_eur: 34.00,
    bgg_rank: 240,
    search_count: 8200,
    item_type: 'boardgame',
  },
  {
    bgg_id: 172224,
    name: 'Exploding Kittens',
    alternate_names: ['Gatitos Explosivos'],
    thumbnail: 'https://cf.geekdo-images.com/ExplodingKittens.jpg',
    image: 'https://cf.geekdo-images.com/ExplodingKittens.jpg',
    description: 'Una versión gatuna alimentada por ruleta rusa con punteros láser, catnip y gatos explosivos.',
    weight: 1.08,
    min_players: 2,
    max_players: 5,
    playing_time: 15,
    base_price_eur: 22.00,
    bgg_rank: 500,
    search_count: 9900,
    item_type: 'boardgame',
  },
  {
    bgg_id: 284083,
    name: 'The Crew: La Búsqueda del Noveno Planeta',
    alternate_names: ['The Crew Mission Deep Sea'],
    thumbnail: 'https://cf.geekdo-images.com/TheCrew.jpg',
    image: 'https://cf.geekdo-images.com/TheCrew.jpg',
    description: 'Un juego de bazas cooperativo espacial donde los astronautas completan misiones de alta precisión sin comunicación verbal.',
    weight: 1.96,
    min_players: 2,
    max_players: 5,
    playing_time: 20,
    base_price_eur: 18.00,
    bgg_rank: 52,
    search_count: 3800,
    item_type: 'boardgame',
  },
];

export const INITIAL_BARCODES: GameBarcode[] = [
  { id: 'gb-01', barcode: '8435407624108', bgg_id: 13, edition_language: 'es', publisher_name: 'Devir' },
  { id: 'gb-02', barcode: '8435407639102', bgg_id: 382910, edition_language: 'es', publisher_name: 'Zygomatic' },
  { id: 'gb-03', barcode: '8435407624122', bgg_id: 926, edition_language: 'es', publisher_name: 'Devir' },
  { id: 'gb-04', barcode: '8435407621107', bgg_id: 822, edition_language: 'es', publisher_name: 'Devir' },
  { id: 'gb-05', barcode: '8435407628809', bgg_id: 266192, edition_language: 'es', publisher_name: 'Maldito Games' },
  { id: 'gb-06', barcode: '8435407609204', bgg_id: 14996, edition_language: 'es', publisher_name: 'Days of Wonder' },
  { id: 'gb-07', barcode: '8435407619807', bgg_id: 230802, edition_language: 'es', publisher_name: 'Asmodee' },
  { id: 'gb-08', barcode: '8435407615007', bgg_id: 167791, edition_language: 'es', publisher_name: 'Maldito Games' },
];

export const INITIAL_MAPPINGS: MerchantProductMapping[] = [
  { id: 'mpm-01', store_id: 'store-ficha-01', merchant_sku: 'DEV-CATAN-ES', bgg_id: 13, is_verified: true },
  { id: 'mpm-02', store_id: 'store-mundomeeple-02', merchant_sku: 'CATAN-BASE-MX', bgg_id: 13, is_verified: true },
  { id: 'mpm-03', store_id: 'store-rollgames-03', merchant_sku: 'SPOT-IT-CATAN', bgg_id: 382910, is_verified: true },
];

export const INITIAL_OFFERS: StoreGameOffer[] = [
  {
    id: 'offer-01',
    store_id: 'store-ficha-01',
    bgg_id: 13,
    store_product_url: 'https://fichaydado.com/products/catan-energias-en-espanol-juego-de-mesa',
    price: 1275.00,
    stock: 12,
    edition_language: 'es',
    is_featured: true,
    match_confidence: 1.00,
    match_tier: 1,
  },
  {
    id: 'offer-02',
    store_id: 'store-hobbyguild-22',
    bgg_id: 13,
    store_product_url: 'https://hobbyguild.mx/products/catan-espanol',
    price: 850.00,
    stock: 5,
    edition_language: 'es',
    is_featured: false,
    match_confidence: 1.00,
    match_tier: 1,
  },
  {
    id: 'offer-03',
    store_id: 'store-bundaba-07',
    bgg_id: 13,
    store_product_url: 'https://bundaba.com.mx/products/catan',
    price: 750.00,
    stock: 8,
    edition_language: 'es',
    is_featured: false,
    match_confidence: 1.00,
    match_tier: 1,
  },
  {
    id: 'offer-04',
    store_id: 'store-alfaydelta-06',
    bgg_id: 13,
    store_product_url: 'https://alfaydelta.com/products/catan-edicion-de-viaje',
    price: 950.00,
    stock: 4,
    edition_language: 'es',
    is_featured: false,
    match_confidence: 1.00,
    match_tier: 1,
  },
  {
    id: 'offer-05',
    store_id: 'store-rollgames-03',
    bgg_id: 382910,
    store_product_url: 'https://rollgames.mx/products/dobble-catan',
    price: 349.00,
    stock: 15,
    edition_language: 'es',
    is_featured: false,
    match_confidence: 1.00,
    match_tier: 1,
  },
  {
    id: 'offer-06',
    store_id: 'store-hobbyguild-22',
    bgg_id: 926,
    store_product_url: 'https://hobbyguild.mx/products/catan-expansion-ciudades-y-caballeros-espanol',
    price: 800.00,
    stock: 6,
    edition_language: 'es',
    is_featured: false,
    match_confidence: 1.00,
    match_tier: 1,
  },
  {
    id: 'offer-07',
    store_id: 'store-hobbyguild-22',
    bgg_id: 822,
    store_product_url: 'https://hobbyguild.mx/products/carcassonne-base',
    price: 600.00,
    stock: 10,
    edition_language: 'es',
    is_featured: true,
    match_confidence: 1.00,
    match_tier: 1,
  },
  {
    id: 'offer-08',
    store_id: 'store-catito-13',
    bgg_id: 822,
    store_product_url: 'https://catitogames.com/products/carcassonne',
    price: 799.00,
    stock: 7,
    edition_language: 'es',
    is_featured: false,
    match_confidence: 1.00,
    match_tier: 1,
  },
  {
    id: 'offer-09',
    store_id: 'store-vonkraken-47',
    bgg_id: 822,
    store_product_url: 'https://vonkraken.com.mx/products/1772579885',
    price: 1350.00,
    stock: 5,
    edition_language: 'es',
    is_featured: false,
    match_confidence: 1.00,
    match_tier: 1,
  },
  {
    id: 'offer-10',
    store_id: 'store-bundaba-07',
    bgg_id: 266192,
    store_product_url: 'https://bundaba.com.mx/products/wingspan',
    price: 1200.00,
    stock: 9,
    edition_language: 'es',
    is_featured: true,
    match_confidence: 1.00,
    match_tier: 1,
  },
  {
    id: 'offer-11',
    store_id: 'store-hobbyguild-22',
    bgg_id: 266192,
    store_product_url: 'https://hobbyguild.mx/products/wingspan-espanol',
    price: 1245.00,
    stock: 6,
    edition_language: 'es',
    is_featured: false,
    match_confidence: 1.00,
    match_tier: 1,
  },
  {
    id: 'offer-12',
    store_id: 'store-mundomeeple-02',
    bgg_id: 266192,
    store_product_url: 'https://mundomeeplestore.com/products/wingspan',
    price: 1450.00,
    stock: 4,
    edition_language: 'es',
    is_featured: false,
    match_confidence: 1.00,
    match_tier: 1,
  },
  {
    id: 'offer-13',
    store_id: 'store-catito-13',
    bgg_id: 14996,
    store_product_url: 'https://catitogames.com/products/aventureros-al-tren-europa',
    price: 1299.00,
    stock: 8,
    edition_language: 'es',
    is_featured: true,
    match_confidence: 1.00,
    match_tier: 1,
  },
  {
    id: 'offer-13b',
    store_id: 'store-rollgames-03',
    bgg_id: 14996,
    store_product_url: 'https://rollgames.mx/products/aventureros-al-tren-europa',
    price: 1349.00,
    stock: 5,
    edition_language: 'es',
    is_featured: false,
    match_confidence: 1.00,
    match_tier: 1,
  },
  {
    id: 'offer-14',
    store_id: 'store-alfaydelta-06',
    bgg_id: 167791,
    store_product_url: 'https://alfaydelta.com/products/terraforming-mars',
    price: 1400.00,
    stock: 5,
    edition_language: 'es',
    is_featured: false,
    match_confidence: 1.00,
    match_tier: 1,
  },
  {
    id: 'offer-15',
    store_id: 'store-mandrake-36',
    bgg_id: 230802,
    store_product_url: 'https://mandrakejuegos.com/products/azul',
    price: 850.00,
    stock: 6,
    edition_language: 'es',
    is_featured: true,
    match_confidence: 1.00,
    match_tier: 1,
  },
  {
    id: 'offer-16',
    store_id: 'store-kukara-31',
    bgg_id: 230802,
    store_product_url: 'https://kukaragames.com/products/azul-juego-de-estrategia-de-2-a-4-jugadores',
    price: 1150.00,
    stock: 4,
    edition_language: 'es',
    is_featured: false,
    match_confidence: 1.00,
    match_tier: 1,
  },
];

export const INITIAL_QUEUE_ITEMS: QueueItem[] = [
  {
    id: 'queue-01',
    store_id: 'store-mundomeeple-02',
    ean: '8435407639999',
    title: 'Catan Edición 3D Coleccionista (Preventa)',
    store_product_url: 'https://mundomeeplestore.com/products/catan-3d-collector',
    status: 'pending',
    match_confidence: 0.82,
    suggested_bgg_id: 13,
  },
  {
    id: 'queue-02',
    store_id: 'store-ficha-01',
    ean: '8435407641111',
    title: 'Munchkin Catan Crossover Pack',
    store_product_url: 'https://fichaydado.com/products/munchkin-catan',
    status: 'pending',
    match_confidence: 0.75,
    suggested_bgg_id: 13,
  },
];
