export interface MockStore {
  id: string;
  slug?: string;
  name: string;
  country: string; // ES, PT, MX, BR, AR, CO, CL, PE, UY
  logo_url: string | null;
  rating: number;
  review_count: number;
  website: string;
  default_shipping_flat: number;
  free_shipping_threshold: number | null;
  city?: string;
  address?: string;
  description?: string;
  specialties?: string[];
}

export interface MockGame {
  bgg_id: number;
  name: string;
  thumbnail: string;
  image?: string;
  description?: string;
  weight: number;
  min_players: number;
  max_players: number;
  playing_time: number;
  base_price_eur: number; // Base price reference in EUR equivalent
}

export const MOCK_IBEROAMERICAN_STORES: MockStore[] = [
  {
    id: '11111111-1111-1111-1111-111111111101',
    slug: 'store-mx-01',
    name: 'Ficha y Dado',
    country: 'MX',
    logo_url: null,
    rating: 4.9,
    review_count: 840,
    website: 'https://fichaydado.com',
    default_shipping_flat: 99.0,
    free_shipping_threshold: 1200.0,
    city: 'Ciudad de México, CDMX',
    address: 'Showroom en CDMX y envíos diarios a toda la República Mexicana',
    description: 'Una de las tiendas de juegos de mesa más consolidadas de México, destacada por su inmenso surtido de eurogames pesados, preventas internacionales y atención especializada al aficionado.',
    specialties: ['Eurogames pesados', 'Preventas exclusivas', 'Juegos importados', 'Accesorios de hobby'],
  },
  {
    id: '11111111-1111-1111-1111-111111111102',
    slug: 'store-mx-02',
    name: 'Mundo Meeple Store',
    country: 'MX',
    logo_url: null,
    rating: 4.8,
    review_count: 620,
    website: 'https://mundomeeplestore.com',
    default_shipping_flat: 110.0,
    free_shipping_threshold: 1499.0,
    city: 'Monterrey, N.L.',
    address: 'Centro de distribución en el norte y envíos a todo México',
    description: 'Tienda apasionada con una excelente selección de juegos modernos, eurogames familiares accesibles y espectaculares rompecabezas mecánicos en 3D.',
    specialties: ['Juegos modernos', 'Rompecabezas 3D', 'Juegos familiares', 'Novedades editoriales'],
  },
  {
    id: '11111111-1111-1111-1111-111111111103',
    slug: 'store-mx-03',
    name: 'Roll Games',
    country: 'MX',
    logo_url: null,
    rating: 4.9,
    review_count: 910,
    website: 'https://rollgames.mx',
    default_shipping_flat: 120.0,
    free_shipping_threshold: 1500.0,
    city: 'Ciudad de México, CDMX',
    address: 'Colonia Roma / Insurgentes Sur, CDMX (Tienda y Board Game Café)',
    description: 'Una vibrante comunidad y board game café en la Ciudad de México con una enorme ludoteca abierta y un catálogo repleto de novedades recién salidas del horno.',
    specialties: ['Board Game Café', 'Juegos de fiesta', 'Eventos en vivo', 'Novedades importadas'],
  },
  {
    id: '11111111-1111-1111-1111-111111111104',
    slug: 'store-mx-04',
    name: 'Con T de Tlacuache',
    country: 'MX',
    logo_url: null,
    rating: 4.9,
    review_count: 530,
    website: 'https://tdetlacuache.com',
    default_shipping_flat: 105.0,
    free_shipping_threshold: 1199.0,
    city: 'Guadalajara, JAL.',
    address: 'Despachos express desde el occidente del país a toda la República',
    description: 'El refugio para los jugones de hueso colorado: especialistas en estrategia profunda, títulos independientes difíciles de conseguir y protección premium para tus juegos.',
    specialties: ['Estrategia pesada', 'Títulos independientes', 'Hobby y pinturas', 'Fundas premium'],
  },
  {
    id: '11111111-1111-1111-1111-111111111106',
    slug: 'store-mx-06',
    name: 'Quantum Boardgames',
    country: 'MX',
    logo_url: null,
    rating: 4.9,
    review_count: 480,
    website: 'https://quantumboardgames.com',
    default_shipping_flat: 110.0,
    free_shipping_threshold: 1299.0,
    city: 'Querétaro, QRO.',
    address: 'Tienda en línea y punto de entrega en Querétaro con envíos nacionales',
    description: 'Buscamos la perfección lúdica: joyas abstractas, eurogames elegantes de alta escuela y novedades europeas seleccionadas con rigor.',
    specialties: ['Abstractos elegantes', 'Eurogames de alta escuela', 'Juegos para 2 jugadores', 'Importaciones europeas'],
  },
  {
    id: '11111111-1111-1111-1111-111111111107',
    slug: 'store-mx-07',
    name: 'Alfa y Delta',
    country: 'MX',
    logo_url: null,
    rating: 4.8,
    review_count: 590,
    website: 'https://alfaydelta.com',
    default_shipping_flat: 99.0,
    free_shipping_threshold: 1199.0,
    city: 'Mérida, YUC.',
    address: 'Envíos a la Península de Yucatán y a todo el país con empaque reforzado',
    description: 'Desde el sureste mexicano, llevamos la pasión por los juegos de mesa modernos a tu hogar con asesoría cercana y envíos extra protegidos.',
    specialties: ['Asesoría personalizada', 'Juegos de campaña', 'Fillers rápidos', 'Empaque reforzado'],
  },
  {
    id: '11111111-1111-1111-1111-111111111108',
    slug: 'store-mx-08',
    name: 'Bundaba',
    country: 'MX',
    logo_url: null,
    rating: 4.9,
    review_count: 640,
    website: 'https://bundaba.com.mx',
    default_shipping_flat: 105.0,
    free_shipping_threshold: 1399.0,
    city: 'Tijuana, B.C.',
    address: 'Logística ágil desde la frontera norte hacia todos los rincones de México',
    description: 'Conectando fronteras a través del juego: especialistas en novedades internacionales, exitosos proyectos de Kickstarter y juegos familiares entrañables.',
    specialties: ['Novedades internacionales', 'Proyectos Kickstarter', 'Juegos familiares', 'Juegos de cartas'],
  },
];

export const VERIFIED_MEXICAN_STORES = MOCK_IBEROAMERICAN_STORES;

export const MOCK_GAMES: MockGame[] = [
  {
    bgg_id: 421285,
    name: 'Excalibur',
    thumbnail: 'https://cf.geekdo-images.com/W3Bsga_uLP9kO91gZ7H8yw__thumb/img/8a9HeqFydO7Uun_le9bXWPnidcA=/fit-in/200x150/filters:strip_icc()/pic2419375.jpg',
    image: 'https://cf.geekdo-images.com/W3Bsga_uLP9kO91gZ7H8yw__original/img/oRc0AomWA9ZtFqQDZiZbIyKE1j0=/0x0/filters:format(png)/pic2419375.jpg',
    description: 'Excalibur de Roxley Games es un elegante juego táctico de intriga legendaria y enfrentamientos decisivos, donde cada movimiento define el destino del reino.',
    weight: 2.6,
    min_players: 2,
    max_players: 4,
    playing_time: 45,
    base_price_eur: 45.0,
  },
  {
    bgg_id: 204583,
    name: 'Kingdomino',
    thumbnail: 'https://cf.geekdo-images.com/x3zxjr-Vw5iWnBDP36yY4A__small/img/1upgE6zU9E_22a1B8v_H2tJ0V_8=/fit-in/200x150/filters:strip_icc()/pic3132685.png',
    image: 'https://cf.geekdo-images.com/x3zxjr-Vw5iWnBDP36yY4A__original/img/oRc0AomWA9ZtFqQDZiZbIyKE1j0=/0x0/filters:format(png)/pic3132685.png',
    description: 'En Kingdomino, encarnas a un Señor que busca nuevas tierras para expandir su reino. Debes explorar todos los terrenos, campos de trigo, lagos y montañas para localizar las mejores parcelas.',
    weight: 1.2,
    min_players: 2,
    max_players: 4,
    playing_time: 15,
    base_price_eur: 20.0,
  },
  {
    bgg_id: 124742,
    name: 'Concordia',
    thumbnail: 'https://cf.geekdo-images.com/gK9J2L7-9l5G9y4S_N1G7Q__small/img/3-v46lX-9X9-L16M4W85A9W68Ww=/fit-in/200x150/filters:strip_icc()/pic2004240.jpg',
    image: 'https://cf.geekdo-images.com/gK9J2L7-9l5G9y4S_N1G7Q__original/img/oRc0AomWA9ZtFqQDZiZbIyKE1j0=/0x0/filters:format(png)/pic2004240.jpg',
    description: 'En Concordia, los jugadores lideran familias romanas para desarrollar su red comercial por todo el Imperio. Envían colonos, construyen casas y producen valiosos recursos como vino, telas y hierro.',
    weight: 3.0,
    min_players: 2,
    max_players: 5,
    playing_time: 100,
    base_price_eur: 50.0,
  },
  {
    bgg_id: 13,
    name: 'Catan',
    thumbnail: 'https://cf.geekdo-images.com/0XODRpReiZBFUffEcqT5-Q__small/img/SNVfF23OQafv3u8xdFolJnMkBoM=/fit-in/200x150/filters:strip_icc()/pic9156909.png',
    image: 'https://cf.geekdo-images.com/0XODRpReiZBFUffEcqT5-Q__original/img/oRc0AomWA9ZtFqQDZiZbIyKE1j0=/0x0/filters:format(png)/pic9156909.png',
    description: 'En Catan, los jugadores intentan ser la fuerza dominante en la isla construyendo colonias, ciudades y carreteras mediante el comercio de recursos como lana, cereales, madera, ladrillo y mineral.',
    weight: 2.3,
    min_players: 3,
    max_players: 4,
    playing_time: 120,
    base_price_eur: 37.50,
  },
  {
    bgg_id: 266192,
    name: 'Wingspan',
    thumbnail: 'https://cf.geekdo-images.com/yLZJCVLlIx4c7eJEWUNJ7w__small/img/VNToqgS2-pOGU6MuvIkMPKn_y-s=/fit-in/200x150/filters:strip_icc()/pic4458123.jpg',
    image: 'https://cf.geekdo-images.com/yLZJCVLlIx4c7eJEWUNJ7w__original/img/cI782Zis9cT66j2MjSHKJGnFPNw=/0x0/filters:format(jpeg)/pic4458123.jpg',
    description: 'Eres un entusiasta de las aves: investigador, observador de aves, ornitólogo o coleccionista que busca atraer las mejores y más hermosas especies a su red de reservas naturales.',
    weight: 2.46,
    min_players: 1,
    max_players: 5,
    playing_time: 70,
    base_price_eur: 42.0,
  },
  {
    bgg_id: 291453,
    name: 'Scout',
    thumbnail: 'https://cf.geekdo-images.com/39A86QJ2FqYlKzCj2p_Q3A__small/img/3nQfL_s-t3A=/fit-in/200x150/filters:strip_icc()/pic6521577.jpg',
    image: 'https://cf.geekdo-images.com/39A86QJ2FqYlKzCj2p_Q3A__original/img/3nQfL_s-t3A=/pic6521577.jpg',
    description: 'Scout es un juego de cartas de Oink Games en el que los jugadores asumen el rol de directores de circo que reclutan artistas y organizan espectáculos compitiendo por la mejor combinación.',
    weight: 1.3,
    min_players: 2,
    max_players: 5,
    playing_time: 20,
    base_price_eur: 18.0,
  },
  {
    bgg_id: 167791,
    name: 'Terraforming Mars',
    thumbnail: 'https://cf.geekdo-images.com/wg9oOLcsKvDesSUdZQ4rxw__small/img/BTxqxgYay5tHJfVoJ2NF5g43_gA=/fit-in/200x150/filters:strip_icc()/pic3536616.jpg',
    image: 'https://cf.geekdo-images.com/wg9oOLcsKvDesSUdZQ4rxw__original/img/thIqWDnH9utKuoKVEUqveDixprI=/0x0/filters:format(jpeg)/pic3536616.jpg',
    description: 'En el siglo XXIV, la humanidad comienza a terraformar el planeta Marte. Corporaciones gigantes lideradas por el Gobierno Mundial invierten recursos para elevar la temperatura, el oxígeno y los océanos.',
    weight: 3.24,
    min_players: 1,
    max_players: 5,
    playing_time: 120,
    base_price_eur: 54.95,
  },
  {
    bgg_id: 169786,
    name: 'Scythe',
    thumbnail: 'https://cf.geekdo-images.com/7k_nOxpO9OGIjhLq2BUZdA__small/img/eQ69OEDdjYjfKg6q5Navee87skU=/fit-in/200x150/filters:strip_icc()/pic3163924.jpg',
    image: 'https://cf.geekdo-images.com/7k_nOxpO9OGIjhLq2BUZdA__original/img/HlDb9F365w0tSP8uD1vf1pfniQE=/0x0/filters:format(jpeg)/pic3163924.jpg',
    description: 'Scythe es un juego de construcción de motores de estrategia ambientado en una historia alternativa en la Europa de los años 1920 tras la Gran Guerra.',
    weight: 3.44,
    min_players: 1,
    max_players: 5,
    playing_time: 115,
    base_price_eur: 69.90,
  },
  {
    bgg_id: 342942,
    name: 'Ark Nova',
    thumbnail: 'https://cf.geekdo-images.com/SoU8p28Sk1s8MSvoM4N8pQ__small/img/4KuHNTWSMPf8vTNDKSRMMI3oOv8=/fit-in/200x150/filters:strip_icc()/pic6293412.jpg',
    image: 'https://cf.geekdo-images.com/SoU8p28Sk1s8MSvoM4N8pQ__original/img/g4S18szTdrXCdIwVKzMKrZrYAcM=/0x0/filters:format(jpeg)/pic6293412.jpg',
    description: 'En Ark Nova planificarás y diseñarás un zoológico científicamente administrado con las instalaciones más avanzadas y proyectos de conservación global.',
    weight: 3.76,
    min_players: 1,
    max_players: 4,
    playing_time: 150,
    base_price_eur: 62.50,
  },
  {
    bgg_id: 295947,
    name: 'Cascadia',
    thumbnail: 'https://cf.geekdo-images.com/MjeJZfulbsM1DSV3DrGJYA__small/img/tVSFjSxYEcw7sKj3unIIQV8kxoc=/fit-in/200x150/filters:strip_icc()/pic5100691.jpg',
    image: 'https://cf.geekdo-images.com/MjeJZfulbsM1DSV3DrGJYA__original/img/B374C04Eip7fmQBGJzgiOTp-jyQ=/0x0/filters:format(jpeg)/pic5100691.jpg',
    description: 'Cascadia es un juego de colocación de losetas y selección de fichas que presenta los hábitats y la vida silvestre del noroeste del Pacífico.',
    weight: 1.95,
    min_players: 1,
    max_players: 4,
    playing_time: 45,
    base_price_eur: 34.90,
  },
  {
    bgg_id: 224517,
    name: 'Brass: Birmingham',
    thumbnail: 'https://cf.geekdo-images.com/x3zxjr-Vw5iU4yDPg70Jgw__small/img/o18rjEemoWaVru9Y2TyPwuIaRfE=/fit-in/200x150/filters:strip_icc()/pic3490053.jpg',
    image: 'https://cf.geekdo-images.com/x3zxjr-Vw5iU4yDPg70Jgw__original/img/FpyxH41Y6_ROoePAilPNEhXnzO8=/0x0/filters:format(jpeg)/pic3490053.jpg',
    description: 'Brass: Birmingham es un juego de estrategia económica que cuenta la historia de emprendedores que compiten en Birmingham durante la revolución industrial.',
    weight: 3.89,
    min_players: 2,
    max_players: 4,
    playing_time: 120,
    base_price_eur: 64.90,
  },
  {
    bgg_id: 316554,
    name: 'Dune: Imperium',
    thumbnail: 'https://cf.geekdo-images.com/PhjygpWSo-0labGrPBMyyg__small/img/JGgY-nBmkyB8WRp8vcoBLlNMQ5U=/fit-in/200x150/filters:strip_icc()/pic5666597.jpg',
    image: 'https://cf.geekdo-images.com/PhjygpWSo-0labGrPBMyyg__original/img/mZzaBAEEJpMlHWWmC0R6Su0OibQ=/0x0/filters:format(jpeg)/pic5666597.jpg',
    description: 'Dune: Imperium combina la construcción de mazos y la colocación de trabajadores en una profunda estrategia política y militar en Arrakis.',
    weight: 3.04,
    min_players: 1,
    max_players: 4,
    playing_time: 120,
    base_price_eur: 48.50,
  },
  {
    bgg_id: 173346,
    name: '7 Wonders Duel',
    thumbnail: 'https://cf.geekdo-images.com/zdagMskTF7wJBPjX74XsRw__small/img/gV1-ckZSIC-dCxxpq1Y7GmPITzQ=/fit-in/200x150/filters:strip_icc()/pic2576399.jpg',
    image: 'https://cf.geekdo-images.com/zdagMskTF7wJBPjX74XsRw__original/img/Ju836WNSaW7Mab9Vjq2TJ_FqhWQ=/0x0/filters:format(jpeg)/pic2576399.jpg',
    description: 'En 7 Wonders Duel te enfrentarás a un solo rival para liderar una civilización hacia la victoria científica, militar o civil.',
    weight: 2.24,
    min_players: 2,
    max_players: 2,
    playing_time: 30,
    base_price_eur: 24.90,
  },
  {
    bgg_id: 230802,
    name: 'Azul',
    thumbnail: 'https://cf.geekdo-images.com/aPSHJO0d0XOpQR5X-wJonw__small/img/ccsXKrdGJw-YSClWwzVUwk5Nh9Y=/fit-in/200x150/filters:strip_icc()/pic6973671.png',
    image: 'https://cf.geekdo-images.com/aPSHJO0d0XOpQR5X-wJonw__original/img/AkbtYVc6xXJF3c9EUrakklcclKw=/0x0/filters:format(png)/pic6973671.png',
    description: 'En Azul, los jugadores compiten como artesanos para decorar las paredes del Palacio Real de Évora con hermosas losetas.',
    weight: 1.76,
    min_players: 2,
    max_players: 4,
    playing_time: 45,
    base_price_eur: 39.90,
  },
  {
    bgg_id: 237182,
    name: 'Root',
    thumbnail: 'https://cf.geekdo-images.com/JUAUWaVUzeBgzirhZNmHHw__small/img/ACovMZzGGIsBRyEQXFnsT8282NM=/fit-in/200x150/filters:strip_icc()/pic4254509.jpg',
    image: 'https://cf.geekdo-images.com/JUAUWaVUzeBgzirhZNmHHw__original/img/E0s2LvtFA1L5YKk-_44D4u2VD2s=/0x0/filters:format(jpeg)/pic4254509.jpg',
    description: 'Root es un juego de aventuras y guerra asimétrica donde los jugadores luchan por el control de un vasto bosque.',
    weight: 3.78,
    min_players: 2,
    max_players: 4,
    playing_time: 90,
    base_price_eur: 58.00,
  },
  {
    bgg_id: 822,
    name: 'Carcassonne',
    thumbnail: 'https://cf.geekdo-images.com/peUgu3A20LRmAXAMyDQfpQ__small/img/oEEslN-EGqh82sNI6Aj4_MFXYg0=/fit-in/200x150/filters:strip_icc()/pic8621446.jpg',
    image: 'https://cf.geekdo-images.com/peUgu3A20LRmAXAMyDQfpQ__original/img/bP18m_PYjyFOv1IBGgMOteQUneA=/0x0/filters:format(jpeg)/pic8621446.jpg',
    description: 'Carcassonne es un juego clásico de colocación de losetas en el que los jugadores construyen el paisaje medieval francés de caminos, ciudades y monasterios.',
    weight: 1.90,
    min_players: 2,
    max_players: 5,
    playing_time: 45,
    base_price_eur: 29.90,
  },
  {
    bgg_id: 373106,
    name: 'Sky Team',
    thumbnail: 'https://cf.geekdo-images.com/Hn2eE8fLzX66m1y90eP34Q__small/img/xP_K3p7lHkE6y-F3x3x-4lR_3n4=/fit-in/200x150/filters:strip_icc()/pic7541603.jpg',
    image: 'https://cf.geekdo-images.com/Hn2eE8fLzX66m1y90eP34Q__original/img/gL_3wZ8Y61oM_m5tQv8qY_k0zM4=/0x0/filters:format(jpeg)/pic7541603.jpg',
    description: 'En Sky Team, eres un equipo de piloto y copiloto en los mandos de un avión comercial. Coordinen sus dados en silencio y aterricen a salvo en aeropuertos del todo el mundo.',
    weight: 2.05,
    min_players: 2,
    max_players: 2,
    playing_time: 20,
    base_price_eur: 29.90,
  },
  {
    bgg_id: 359871,
    name: 'Arcs',
    thumbnail: 'https://cf.geekdo-images.com/3q1h8g7H2v4M5t6y0JvD5A__small/img/7k9h8g1H3v2M4t5y0JvD5A=/fit-in/200x150/filters:strip_icc()/pic7923485.jpg',
    image: 'https://cf.geekdo-images.com/3q1h8g7H2v4M5t6y0JvD5A__original/img/9k8h7g6H5v4M3t2y1JvD0A=/0x0/filters:format(jpeg)/pic7923485.jpg',
    description: 'En Arcs, lideras una sociedad espacial al borde del colapso. Un juego de ciencia ficción épico con cartas de acción multifunción y combates espaciales.',
    weight: 3.55,
    min_players: 2,
    max_players: 4,
    playing_time: 120,
    base_price_eur: 64.90,
  },
  {
    bgg_id: 386618,
    name: 'Faraway',
    thumbnail: 'https://cf.geekdo-images.com/8k7h9g1H2v3M4t5y0JvD5A__small/img/1k8h9g7H2v4M5t6y0JvD5A=/fit-in/200x150/filters:strip_icc()/pic7541999.jpg',
    image: 'https://cf.geekdo-images.com/8k7h9g1H2v3M4t5y0JvD5A__original/img/2k7h8g9H1v3M4t5y0JvD5A=/0x0/filters:format(jpeg)/pic7541999.jpg',
    description: 'Explora el misterioso continente de Alula y coloca cartas en fila para puntuar en orden inverso en un juego de cartas brillante y desafiante.',
    weight: 1.68,
    min_players: 2,
    max_players: 6,
    playing_time: 25,
    base_price_eur: 21.90,
  },
  {
    bgg_id: 397598,
    name: 'Dune: Imperium - Uprising',
    thumbnail: 'https://cf.geekdo-images.com/4k7h8g9H1v2M3t5y0JvD5A__small/img/6k8h9g7H2v3M4t5y0JvD5A=/fit-in/200x150/filters:strip_icc()/pic7681342.jpg',
    image: 'https://cf.geekdo-images.com/4k7h8g9H1v2M3t5y0JvD5A__original/img/5k7h8g9H1v2M3t4y0JvD5A=/0x0/filters:format(jpeg)/pic7681342.jpg',
    description: 'Continúa la batalla por Arrakis con nuevas mecánicas de espionaje, contratos y gusanos de arena de combate en esta entrega independiente de Dune: Imperium.',
    weight: 3.48,
    min_players: 1,
    max_players: 6,
    playing_time: 120,
    base_price_eur: 59.90,
  },
  {
    bgg_id: 371942,
    name: 'The White Castle',
    thumbnail: 'https://cf.geekdo-images.com/1k7h8g9H2v3M4t5y0JvD5A__small/img/3k8h9g7H1v2M4t5y0JvD5A=/fit-in/200x150/filters:strip_icc()/pic7452183.jpg',
    image: 'https://cf.geekdo-images.com/1k7h8g9H2v3M4t5y0JvD5A__original/img/7k8h9g1H2v3M4t5y0JvD5A=/0x0/filters:format(jpeg)/pic7452183.jpg',
    description: 'Gestiona recursos, cortesanos, guerreros y jardineros dentro del Castillo de Himeji en un eurogame de gestión de dados altamente apretado.',
    weight: 2.85,
    min_players: 1,
    max_players: 4,
    playing_time: 80,
    base_price_eur: 34.90,
  },
  {
    bgg_id: 84876,
    name: 'The Castles of Burgundy',
    thumbnail: 'https://cf.geekdo-images.com/5k7h8g9H1v2M3t4y0JvD5A__small/img/8k7h9g1H2v3M4t5y0JvD5A=/fit-in/200x150/filters:strip_icc()/pic4827038.jpg',
    image: 'https://cf.geekdo-images.com/5k7h8g9H1v2M3t4y0JvD5A__original/img/9k8h7g6H5v4M3t2y1JvD0A=/0x0/filters:format(jpeg)/pic4827038.jpg',
    description: 'Como noble aristócrata en la Francia del siglo XV, guía tu príncipado hacia la prosperidad construyendo asentamientos, comerciando y explotando minas.',
    weight: 3.01,
    min_players: 1,
    max_players: 4,
    playing_time: 90,
    base_price_eur: 44.90,
  },
  {
    bgg_id: 354570,
    name: 'Revive',
    thumbnail: 'https://cf.geekdo-images.com/2k7h8g9H1v3M4t5y0JvD5A__small/img/4k7h8g9H1v2M3t5y0JvD5A=/fit-in/200x150/filters:strip_icc()/pic6831452.jpg',
    image: 'https://cf.geekdo-images.com/2k7h8g9H1v3M4t5y0JvD5A__original/img/1k7h8g9H2v3M4t5y0JvD5A=/0x0/filters:format(jpeg)/pic6831452.jpg',
    description: 'Explora una Tierra helada 5000 años después de la caída de la humanidad. Recluta supervivientes y desbloquea tecnologías ancestrales.',
    weight: 3.42,
    min_players: 1,
    max_players: 4,
    playing_time: 120,
    base_price_eur: 74.90,
  },
  {
    bgg_id: 350184,
    name: 'Earth',
    thumbnail: 'https://cf.geekdo-images.com/9k7h8g1H2v3M4t5y0JvD5A__small/img/6k7h8g9H1v2M3t4y0JvD5A=/fit-in/200x150/filters:strip_icc()/pic6711582.jpg',
    image: 'https://cf.geekdo-images.com/9k7h8g1H2v3M4t5y0JvD5A__original/img/3k7h8g9H1v2M4t5y0JvD5A=/0x0/filters:format(jpeg)/pic6711582.jpg',
    description: 'Crea un ecosistema insular autosuficiente en un juego de construcción de motores con reglas simultáneas y combinaciones infinitas de flora y fauna.',
    weight: 2.89,
    min_players: 1,
    max_players: 5,
    playing_time: 90,
    base_price_eur: 49.90,
  },
  {
    bgg_id: 322289,
    name: "Darwin's Journey",
    thumbnail: 'https://cf.geekdo-images.com/7k8h9g1H2v3M4t5y0JvD5A__small/img/2k7h8g9H1v3M4t5y0JvD5A=/fit-in/200x150/filters:strip_icc()/pic6011421.jpg',
    image: 'https://cf.geekdo-images.com/7k8h9g1H2v3M4t5y0JvD5A__original/img/8k7h9g1H2v3M4t5y0JvD5A=/0x0/filters:format(jpeg)/pic6011421.jpg',
    description: 'Retoma las memorias de Charles Darwin en las Islas Galápagos mediante colocación de trabajadores evolutivos y recolección de especímenes biológicos.',
    weight: 3.82,
    min_players: 1,
    max_players: 4,
    playing_time: 120,
    base_price_eur: 54.90,
  },
  {
    bgg_id: 231733,
    name: 'Obsession',
    thumbnail: 'https://cf.geekdo-images.com/6k7h8g9H1v2M3t4y0JvD5A__small/img/9k7h8g1H2v3M4t5y0JvD5A=/fit-in/200x150/filters:strip_icc()/pic3818141.jpg',
    image: 'https://cf.geekdo-images.com/6k7h8g9H1v2M3t4y0JvD5A__original/img/4k7h8g9H1v2M3t5y0JvD5A=/0x0/filters:format(jpeg)/pic3818141.jpg',
    description: 'Restaura la gloria de una finca rural en la Inglaterra victoriana del siglo XIX organizando elegantes veladas sociales y gestionando a tu leal personal de servicio.',
    weight: 3.12,
    min_players: 1,
    max_players: 4,
    playing_time: 90,
    base_price_eur: 69.90,
  },
  {
    bgg_id: 396790,
    name: 'Nucleum',
    thumbnail: 'https://cf.geekdo-images.com/3k7h8g9H1v2M4t5y0JvD5A__small/img/5k7h8g9H1v2M3t4y0JvD5A=/fit-in/200x150/filters:strip_icc()/pic7638421.jpg',
    image: 'https://cf.geekdo-images.com/3k7h8g9H1v2M4t5y0JvD5A__original/img/1k7h8g9H2v3M4t5y0JvD5A=/0x0/filters:format(jpeg)/pic7638421.jpg',
    description: 'Lidera la revolución industrial atómica en Sajonia construyendo redes ferroviarias y reactores de uranio en este eurogame pesado de alta estrategia.',
    weight: 4.08,
    min_players: 1,
    max_players: 4,
    playing_time: 150,
    base_price_eur: 64.90,
  },
  {
    bgg_id: 391168,
    name: 'Kutná Hora: The City of Silver',
    thumbnail: 'https://cf.geekdo-images.com/2k7h8g9H1v2M3t4y0JvD5A__small/img/8k7h9g1H2v3M4t5y0JvD5A=/fit-in/200x150/filters:strip_icc()/pic7542111.jpg',
    image: 'https://cf.geekdo-images.com/2k7h8g9H1v2M3t4y0JvD5A__original/img/6k7h8g9H1v2M3t4y0JvD5A=/0x0/filters:format(jpeg)/pic7542111.jpg',
    description: 'Únete a los mineros y constructores para levantar la histórica ciudad de plata en Bohemia gestionando una economía dinámica regida por oferta y demanda reales.',
    weight: 3.32,
    min_players: 2,
    max_players: 4,
    playing_time: 120,
    base_price_eur: 59.90,
  },
  {
    bgg_id: 343905,
    name: 'Thunder Road: Vendetta',
    thumbnail: 'https://cf.geekdo-images.com/1k7h8g9H2v3M4t5y0JvD5A__small/img/7k8h9g1H2v3M4t5y0JvD5A=/fit-in/200x150/filters:strip_icc()/pic6312451.jpg',
    image: 'https://cf.geekdo-images.com/1k7h8g9H2v3M4t5y0JvD5A__original/img/9k7h8g1H2v3M4t5y0JvD5A=/0x0/filters:format(jpeg)/pic6312451.jpg',
    description: 'Combate y carreras post-apocalípticas a máxima velocidad. Choca, dispara y sobrevive a los peligros del desierto en este adrenalínico juego de mesa.',
    weight: 2.15,
    min_players: 2,
    max_players: 4,
    playing_time: 60,
    base_price_eur: 59.90,
  },
  {
    bgg_id: 240980,
    name: 'Blood on the Clocktower',
    thumbnail: 'https://cf.geekdo-images.com/9k7h8g1H2v3M4t5y0JvD5A__small/img/2k7h8g9H1v3M4t5y0JvD5A=/fit-in/200x150/filters:strip_icc()/pic4611421.jpg',
    image: 'https://cf.geekdo-images.com/9k7h8g1H2v3M4t5y0JvD5A__original/img/5k7h8g9H1v2M3t4y0JvD5A=/0x0/filters:format(jpeg)/pic4611421.jpg',
    description: 'El rey de los juegos de deducción social y engaño en el pueblo maldito de Ravenswood Bluff, donde incluso los muertos pueden hablar y votar para desenmascarar al demonio.',
    weight: 3.25,
    min_players: 5,
    max_players: 20,
    playing_time: 90,
    base_price_eur: 139.90,
  }
];

// Deprecated synthetic getMockOffersForGame deleted per US-71 (Issue #112).
// Real XML feed data is now served via getRealFeedOffersForGame in real_feed_data.ts.
